### ISSUE TITLE
[Feature Request 🚀] Add a `CITATION.cff`

### ISSUE THREAD

**Issue by SauravMaheshkar** [waqasbhatti/astrobase#100]
Github recently released a [**new feature**](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) where repository owners can add a `CITATION.cff` file making it easy for others to cite the repository. Adding a `CITATION.cff` would make the attribution process very easy and IMO is better than the `CITE.md` file.

**Comment by waqasbhatti** [comment]
Thanks for the suggestion!

Fixed in 0ab29af06497e056802f0d979d24408cec73bc32 and a2c650356de66e1518b5058b5220c9ed38d0cbc1.
