### ISSUE TITLE
periodbase.bls_parallel_pfind: save `nphasebins`

### ISSUE THREAD

**Issue by lgbouma** [waqasbhatti/astrobase#18]
The `blsresult` key of the `resultdict` being returned out to whatever called `bls_parallel_pfind` is currently a list of dictionaries returned by `eebls.f`, of the form
```
{'bestperiod': 153.33159309929854,
 'bestpower': 0.0011432965623006885,
 'power': array([ 0.00082555,  0.00086774,  0.00084304, ...,  0.00061361,
         0.00057821,  0.00059612]),
 'transdepth': 0.015760732761291304,
 'transduration': 0.00529015710163514,
 'transegressbin': 260,
 'transingressbin': 254}
```
These latter two keys can only be converted to epoch times if the number of bins in the folded timeseries at the bestperiod is known. 

This is a one-line commit to just save `nphasebins` to `resultdict`. (But the effort of wrangling my git fork into working order to do it is not currently worth it).

**Comment by waqasbhatti** [comment]
The bls methods now return nfreq, nphasebins, and stepsize:
```python
        resultdict = {
            'bestperiod':finperiods[bestperiodind],
            'bestlspval':finlsp[bestperiodind],
            'nbestpeaks':nbestpeaks,
            'nbestlspvals':nbestlspvals,
            'nbestperiods':nbestperiods,
            'lspvals':lsp,
            'frequencies':frequencies,
            'periods':periods,
            'blsresult':results,
            'stepsize':stepsize,
            'nfreq':nfreq,
            'nphasebins':nphasebins,
            'method':'bls',
        }
```

**Comment by waqasbhatti** [comment]
Also added input min and max transit phase duration for completeness.
