### ISSUE TITLE
prewhiten_magseries code doesn't like the default 'plotfit=None'

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#25]
When running prewhiten_magseries() (in signal.py) with the default value for plotfit (None), I get the following error:

File "<path>", line 178, in prewhiten_magseries
    if plotfit and isinstance(plotfit, str) or isinstance(plotfit, strio):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

When I give a string to plotfit, everything runs fine.

I am on version (0.2.6)

**Comment by waqasbhatti** [comment]
Thanks for noticing this! This looks like a bug. Will investigate.

**Comment by waqasbhatti** [comment]
Fixed in v0.2.7. This was a missing parenthesis in the `if` statement logic chain.
