### ISSUE TITLE
prewhiten_magseries(), possible conflicting optional args

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#27]
When running prewhiten_magseries() in lcfit.py, if the argument fourierorder is specified but fourierparam is left alone, then a warning triggers at line 331 and fourierparam is used to the exclusion of fourierorder (see link below)

https://github.com/waqasbhatti/astrobase/blob/master/astrobase/varbase/lcfit.py#L331

fourierorder can be used to the exclusion of fourierparam if fourierparam is set to, e.g., an empty list.  However, it seems a little problematic that setting one optional argument without resetting another one from its default value makes the freshly set optional argument unused.  It took me a little bit to notice this behavior, even though a warning does get displayed when both arguments are set.  Given the current defaults (fourierparam set, fourierorder not set), it may make more sense for the behavior when both get set to be that fourierorder is given preference over fourierparam.  Or maybe the default values of both should be unset, and then the code, if it detects both are still unset, then assigned fourierparam to have its current default value.

**Comment by waqasbhatti** [comment]
Yes, I've been meaning to fix this for a while now. I think the fourierorder over fourierparams preference in the kwargs makes more sense generally, so will set it up that way.

**Comment by waqasbhatti** [comment]
Fixed in v0.2.7. The default behavior now is to have fourierparams=None and fourierorder=None. If both are specified or neither are specified, the fourierorder kwarg is automatically set to 3.
