### ISSUE TITLE
Incorrect comment?

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#29]
https://github.com/waqasbhatti/astrobase/blob/988c3cdd4331aae2abba4f64f6dd1c4561441200/astrobase/varbase/signals.py#L169

The comment on this line states that these things are in phase order; looking through the code and at the output though, I believe they are in time order.  The data was in phase order earlier on but they got changed.

**Comment by waqasbhatti** [comment]
Yep, they're in time order. I'll fix the comment.

**Comment by waqasbhatti** [comment]
Fixed in v0.2.7.
