### ISSUE TITLE
plotbase.make_checkplot should also output to a JSON file

### ISSUE THREAD

**Issue by waqasbhatti** [waqasbhatti/astrobase#3]
Said JSON file will contain:

- objectinfo
- period-search info (LSP peaks, best periods, etc.)
- base64 or binary representations of the LSP and LC plots

This is so a future version of checkplot-viewer can read these JSON files and generate an interactive webpage instead of just showing the checkplot PNG. The webpage should have options to mark objects as interesting, etc. and output these selections and extra metadata into another JSON file (or perhaps just use the browser localstorage).

**Comment by waqasbhatti** [comment]
Copied from the latest commit:

We now have a checkplot.checkplot_pickle function. This can take in lspinfo dicts from multiple period finder methods for an object, and generate a gzipped pickle containing the object info,
finder chart, mag series plot, and for each lspinfo dict: a periodogram, and phased mag series plots for up to however many 'best' peaks the user wants.

This is intended for use with the more advanced checkplot viewer to be implemented as a Tornado webapp: checkplotserver. This will also enable updating varinfo and objectinfo to set the
object's best periods and epochs, and tags based on variability type and object type.

Remaining stuff to do in checkplot.py: write a checkplot pickle file to PNG function that replicates the functionality of twolsp_checkplot_png for arbitrary number of period-finding methods. This will look something like:

```
[    finder    ] [  objectinfo  ] [ variableinfo ] [ unphased LC  ]
[ periodogram1 ] [ phased LC P1 ] [ phased LC P2 ] [ phased LC P3 ]
[ periodogram2 ] [ phased LC P1 ] [ phased LC P2 ] [ phased LC P3 ]
[ periodogramN ] [ phased LC P1 ] [ phased LC P2 ] [ phased LC P3 ]
```
for up to N independent period-finding methods producing:

  - periodogram1,2,3...N: the periodograms from each method
  - phased LC P1,P2,P3: the phased lightcurves using the best 3 peaks in each periodogram

I'll work on the checkplotserver next.

**Comment by waqasbhatti** [comment]
Continuing work on the checkplotserver UI. Here's what it looks like at the moment:

![checkplot server](https://cloud.githubusercontent.com/assets/1868184/21912719/a417cb80-d8f5-11e6-8851-a8925ca4476a.png)

Working:
- on-demand load of checkplot file list
- on-demand load of checkplot pickle
- images from checkplot pickle straight to UI via base64 decoding

Next:
- adding in variability info from checkplot pickle
- adding in periodograms and phased LC plots for each period-finding method in checkplot pickle
- saving changes on-the-fly back to the checkplot pickle

**Comment by lgbouma** [comment]
Big fan of this. Will probably make what I'm currently running -- just eb_checkplot .pngs over the ~20 fields you've given me -- redundant. That said, the pngs may still help fine-tune cuts on the periodicity search to reduce the number of obviously-not-EBs. E.g., finding wide peaks in the periodograms from stellar rotation, finding harmonics of 1-day, cutting through things that have too-few points in the LC, etc., and then sorting appropriately. TBD!

**Comment by waqasbhatti** [comment]
Some more progress:

![checkplot server](https://cloud.githubusercontent.com/assets/1868184/21950102/aed16da8-d9c5-11e6-9bc3-209c3c9554c9.png)

Will finish this up this weekend.

**Comment by waqasbhatti** [comment]
Related to this effort, checkplot_pickle is super slow when writing pickles. It takes about 3 seconds to a write one, and about 300 msec to read one in Python 3.6, and about 12 seconds to write one and about 400 msec to read one in Python 2.7. I did some profiling using ipython's %prun and it turns out the gzip function is responsible for the slow writes. Leaving this out makes the pickle write MUCH faster. It also appears that we don't save much space gzipping the pickles: 29 MB vs 35 MB for protocol v3 pickles from Python 3.6. 

Profiling in Python 3.6:

```python
In [53]: %prun with gzip.open('test.pkl.gz','wb') as outfd: pickle.dump(xdict,outfd,protocol=3)
         56 function calls in 2.386 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    2.264    2.264    2.264    2.264 {method 'compress' of 'zlib.Compress' objects}
        1    0.045    0.045    2.374    2.374 {built-in method _pickle.dump}
        2    0.037    0.018    0.037    0.018 {built-in method zlib.crc32}
       11    0.026    0.002    0.026    0.002 {method 'write' of '_io.BufferedWriter' objects}
        1    0.007    0.007    0.007    0.007 {built-in method io.open}
        1    0.005    0.005    0.005    0.005 {method 'close' of '_io.BufferedWriter' objects}
        1    0.001    0.001    2.329    2.329 gzip.py:247(write)

In [55]: %prun with open('test.pkl','wb') as outfd: pickle.dump(xdict,outfd,protocol=3)
         5 function calls in 0.124 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.109    0.109    0.109    0.109 {built-in method _pickle.dump}
        1    0.011    0.011    0.011    0.011 {built-in method io.open}
        1    0.005    0.005    0.124    0.124 <string>:1(<module>)
        1    0.000    0.000    0.124    0.124 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

Python 3.6 speed tests with gzip on:

```python
In [18]: %timeit -n 20 with gzip.open('test.pkl.gz','wb') as fd: pickle.dump(xdict,fd,protocol=4)
20 loops, best of 3: 2.58 s per loop

In [19]: %timeit -n 20 with gzip.open('test.pkl.gz','wb') as fd: pickle.dump(xdict,fd,protocol=3)
20 loops, best of 3: 2.58 s per loop

In [20]: %timeit -n 20 with gzip.open('test.pkl.gz','wb') as fd: pickle.dump(xdict,fd,protocol=2)
20 loops, best of 3: 13.3 s per loop

In [22]: %timeit -n 20 with gzip.open('test.pkl.gz','wb') as fd: pickle.dump(xdict,fd,protocol=1)
20 loops, best of 3: 13.4 s per loop

In [23]: %timeit -n 20 with gzip.open('test.pkl.gz','wb') as fd: pickle.dump(xdict,fd,protocol=0)
20 loops, best of 3: 2.96 s per loop
```

Python 3.6 speed tests with gzip off:

```python
In [12]: %timeit -n 20 with open('test.pkl','wb') as fd: pickle.dump(xdict,fd,protocol=4)
20 loops, best of 3: 296 ms per loop

In [13]: %timeit -n 20 with open('test.pkl','wb') as fd: pickle.dump(xdict,fd,protocol=3)
20 loops, best of 3: 299 ms per loop

In [14]: %timeit -n 20 with open('test.pkl','wb') as fd: pickle.dump(xdict,fd,protocol=2)
20 loops, best of 3: 583 ms per loop

In [15]: %timeit -n 20 with open('test.pkl','wb') as fd: pickle.dump(xdict,fd,protocol=1)
20 loops, best of 3: 586 ms per loop

In [16]: %timeit -n 20 with open('test.pkl','wb') as fd: pickle.dump(xdict,fd,protocol=0)
20 loops, best of 3: 382 ms per loop
```

Therefore, commit 8f63120fd32c7c21a05cd845ecbd33f5d5588c56 turns off the gzip for the output pickles. checkplot.checkplot_pickle was also refactored in commit d167e278ad811967df55193c70010c96ad3c2eaa to call a checkplot.checkplot_dict function, that does most of the heavy lifting and whose output could go to other (faster) serialization methods in the future.

This should make checkplotviewer.py and anything else that uses checkplot_pickle much more responsive at the cost of ~5-6 MB disk used.

**Comment by waqasbhatti** [comment]
Checkplotserver is done for now (modulo bugfixes). The last bit of functionality added in 5b76bb444d29bd1b3891266c7ef5321ac5d3202c:

## Saving reviewed objects

Added controls for downloading CSVs and JSONs for all objects that have been reviewed and saved. These contain all the info in the objectid, comments, objectinfo, and varinfo keys.

## Keyboard shortcuts

### movement and editing

- ctrl-right: save this, move to next checkplot
- ctrl-left: save this, move to prev checkplot
- ctrl-enter: done, save this and move to next checkplot
- shift-enter: done, just save this checkplot, don't go anywhere
- ctrl-backspace: clear variable tags and variability flag
- ctrl-shift-backspace: clear all info
- ctrl/shift-down: select the next phased LC in the plot tiles, set best period and epoch to those of this selection
- ctrl/shift-up: select the prev phased LC in the plot tiles, set best period and epoch to those of this selection

NOTE: the navigation between phased LC plot tiles is down and then to right.

### setting the variability flag

NOTE: pressing more than one of the shortcut keys below in succession appends tags to the appropriate tag lists. Repeating a tag invocation doesn't add another tag of the same type to the list.

- alt+shift+v: set the flag to 'object is probably a variable'
- alt+shift+n: set the flag to 'object is probably not a variable'
- alt+shift+m: set the flag to 'object is maybe variable, but not sure'
- alt+shift+u: unset the flag, so the variability status is unknown

### tagging variables

- ctrl+shift+1: planet candidate
- ctrl+shift+2: RRab pulsator
- ctrl+shift+3: RRc pulsator
- ctrl+shift+4: starspot rotation
- ctrl+shift+5: flare star
- ctrl+shift+6: contact EB
- ctrl+shift+7: semi-detached EB
- ctrl+shift+8: detached EB
- ctrl+shift+9: weird variability (should use comments box for details)
- ctrl+shift+0: period harmonic (object's actual period may be a harmonic of current best period)

### tagging object types

- alt/cmd+shift+1: white dwarf
- alt/cmd+shift+2: hot star (OB)
- alt/cmd+shift+3: A star
- alt/cmd+shift+4: F or G dwarf
- alt/cmd+shift+5: red giant
- alt/cmd+shift+6: K or M dwarf
- alt/cmd+shift+7: giant star
- alt/cmd+shift+8: dwarf star
- alt/cmd+shift+9: blended with neighbors
- alt/cmd+shift+0: weird object (used for truly strange things)
