### ISSUE TITLE
color_features() preventing printing of mag/color information I do have when I don't have J H or K

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#39]
The series of function calls checkplot_pickle() makes leads eventually to color_features(), which returns a dict without any values if there are no J, H, or K values, or if it can't get the 2MASS DUST extinction info.

For me, this means that even though I have U, B, g, r, and i information, this doesn't get written on the checkplot because I don't have J, H, or K values.  I tried using garbage JHK values (10 for each) but that's when color_feature started complaining about not being able to retrieve 2MASS DUST extinction info.

And unfortunately, 2MASS doesn't have deep enough coverage to have data for even a majority of my objects.

**Comment by waqasbhatti** [comment]
I just added support for this. Do you mind sending over a checkplot pickle that was failing previously? Would be good to test it further.

The following mag keys in the objectinfo dict are recognized out of the box and generate the colors listed, which are all then written to the checkplot pickle and dereddened if requested and possible.

```
    'umag'  -> U mag             -> colors: U-B, U-V, U-g
    'bmag'  -> B mag             -> colors: U-B, B-V
    'vmag'  -> V mag             -> colors: U-V, B-V, V-R, V-I, V-K
    'rmag'  -> R mag             -> colors: V-R, R-I
    'imag'  -> I mag             -> colors: g-I, V-I, R-I, B-I
    'jmag'  -> 2MASS J mag       -> colors: J-H, J-K, g-J, i-J
    'hmag'  -> 2MASS H mag       -> colors: J-H, H-K
    'kmag'  -> 2MASS Ks mag      -> colors: g-Ks, H-Ks, J-Ks, V-Ks
    'sdssu' -> SDSS u mag        -> colors: u-g, u-V
    'sdssg' -> SDSS g mag        -> colors: g-r, g-i, g-K, u-g, U-g, g-J
    'sdssr' -> SDSS r mag        -> colors: r-i, g-r
    'sdssi' -> SDSS i mag        -> colors: r-i, i-z, g-i, i-J, i-W1
    'sdssz' -> SDSS z mag        -> colors: i-z, z-W2, g-z
    'ujmag' -> UKIRT J mag       -> colors: J-H, H-K, J-K, g-J, i-J
    'uhmag' -> UKIRT H mag       -> colors: J-H, H-K
    'ukmag' -> UKIRT K mag       -> colors: g-K, H-K, J-K, V-K
    'irac1' -> Spitzer IRAC1 mag -> colors: i-I1, I1-I2
    'irac2' -> Spitzer IRAC2 mag -> colors: I1-I2, I2-I3
    'irac3' -> Spitzer IRAC3 mag -> colors: I2-I3
    'irac4' -> Spitzer IRAC4 mag -> colors: I3-I4
    'wise1' -> WISE W1 mag       -> colors: i-W1, W1-W2
    'wise2' -> WISE W2 mag       -> colors: W1-W2, W2-W3
    'wise3' -> WISE W3 mag       -> colors: W2-W3
    'wise4' -> WISE W4 mag       -> colors: W3-W4

```
You can add additional bands if you want by giving checkplot_pickle a dict for the new `custom_bandpasses` kwarg. This should look something like:

```
    {
    '<bandpass_key_1>':{'dustkey':'<twomass_dust_key_1>',
                        'label':'<band_label_1>'
                        'colors':[['<bandkey1>-<bandkey2>','<BAND1> - <BAND2>'],
                                  ['<bandkey3>-<bandkey4>','<BAND3> - <BAND4>']]},
    ... other bandpass keys ...
    }
```
where an example for the SDSS r band is:

```
    'sdssr':{'dustkey':'SDSS r',
             'label':'r',
             'colors':[['sdssr-sdssi','r - i'],
                       ['sdssg-sdssr','g - r']]},
```
The docstring has more info: https://github.com/waqasbhatti/astrobase/blob/0fbe66351283a13d673730091f3b1ac38011092d/astrobase/varclass/starfeatures.py#L311

**Comment by joshuawallace** [comment]
Perhaps relevant, I am still running a previous version of astrobase (0.3.8) and I have an object for which I am calculating JHK relative mags from an isochrone fit and distance modulus and I am still getting the same error.  I will send that along.

Thanks!  I will look at the newer version later.

**Comment by waqasbhatti** [comment]
This should work now for git HEAD. Added a test to make sure missing info is correctly handled.
