### ISSUE TITLE
Keep getting " 'str' object has no attribute 'isdecimal' " on line 447 of checkplotlist.py

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#41]
I am trying to generate a checkplotlist but have so far not succeeded.  I keep getting the error

>   File "<path_to>/checkplotlist.py", line 447, in main
>    sortkeys = [(int(x) if x.isdecimal() else x) for x in sortkeys]
>AttributeError: 'str' object has no attribute 'isdecimal'

I have tried the following calls to checkplotlist:

`checkplotlist pkl --search '6045*_*' --sortby 'maxspnr|desc' --outprefix 'checkplot_server_output/' checkplot_pickles_maxspnr/`

`checkplotlist pkl --search '6045*_*' --sortby 'objectid|desc' --outprefix 'checkplot_server_output/' checkplot_pickles_maxspnr/`

`checkplotlist pkl --search '6045*_*' --outprefix 'checkplot_server_output/' checkplot_pickles_maxspnr/`

All fail with this same error.  (A note: 'maxspnr' was a new dictionary key I created for the checkplot dicts for sorting purposes.  When I both tried files that did have this new key and didn't have this new key, neither worked.')

**Comment by joshuawallace** [comment]
Sorry for the quick succession of edits.  To confirm, without the new key checkplotlist is still failing.

**Comment by waqasbhatti** [comment]
Can you email me a few of these checkplot pickles (or point out where they are) so I can take a look?

**Comment by waqasbhatti** [comment]
This was a Python 2 issue I think. Should be fixed in a3967d3bd2f18ad1db362ddafb992fe5affda615

**Comment by joshuawallace** [comment]
Thanks!
