### ISSUE TITLE
Syntax error in checkplotserver source code

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#42]
When I run `checkplotserver` I get the following error:

> $ checkplotserver
>Traceback (most recent call last):
>  File "/nfs/phs3/ar0/S/PROJ/jwallace/venv/bin/checkplotserver", line 11, in <module>
>    load_entry_point('astrobase', 'console_scripts', 'checkplotserver')()
>  File "/nfs/phs3/ar0/S/PROJ/jwallace/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
>    return get_distribution(dist).load_entry_point(group, name)
>  File "/nfs/phs3/ar0/S/PROJ/jwallace/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
>    return ep.load()
>  File "/nfs/phs3/ar0/S/PROJ/jwallace/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
>    return self.resolve()
>  File "/nfs/phs3/ar0/S/PROJ/jwallace/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
>    module = __import__(self.module_name, fromlist=['__name__'], level=0)
>  File "/home/jwallace/astrobase_waqas/astrobase/astrobase/cpserver/checkplotserver.py", line 58, in <module>
>    from . import checkplotserver_handlers as cphandlers
>  File "/home/jwallace/astrobase_waqas/astrobase/astrobase/cpserver/checkplotserver_handlers.py", line 2179
>    **lctoolkwargs,
>                  ^
>SyntaxError: invalid syntax

I deleted the trailing comma in my local copy of the repo but there's something I'm not setting up or compiling properly because it still appears in the error message.

**Comment by waqasbhatti** [comment]
Sorry, this appears to be another Python 2 related bug. Will investigate...

**Comment by waqasbhatti** [comment]
No worries, it's good to get these bugs fixed. I think I can probably work around this. Should have something soon.

**Comment by waqasbhatti** [comment]
It turns out it was the trailing commas after all! Apparently trailing commas in a function call in py2 is illegal but not in py3 (at least not in py 3.6). Weird.

git pull origin master and b070554a8aaf4b33f2c1e3b1b128eed47ed28fb9 should hopefully make it work for you (I got it working with examples of your checkplot pkls under py2).
