### ISSUE TITLE
Can't checkplotserver with only 1 period

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#47]
I've generated some checkplots where I only have one period per method I want to display.  When I try to open these checkplots with checkplotserver I get the following error:

Uncaught exception GET /cp/dGVtcDIvNjA0NTQ2NTYzOTM2MjkzMTU4NF8wLnBrbA== (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:5225', method='GET', uri='/cp/dGVtcDIvNjA0NTQ2NTYzOTM2MjkzMTU4NF8wLnBrbA==', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/jwallace/py36-venv/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/home/jwallace/py36-venv/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/jwallace/py36-venv/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
        yielded = self.gen.send(value)
      File "/home/jwallace/astrobase_waqas/astrobase/astrobase/cpserver/checkplotserver_handlers.py", line 769, in get
        phasedlc1plot = cpdict[key][1]['plot']
    KeyError: 1

Looking into the source code, I believe the error is related to the fact that I only have one period plotted per method.

I tried to hack my way around needing a second and third period but wasn't able to do so successfully.

**Comment by waqasbhatti** [comment]
This should be fixed in the latest commit. A `git pull origin master` should work if you're using astrobase cloned from github.

As part of this, I also added handling of cases where there's no period-finder results at all, so this should work fine as well if it's ever needed (e.g. just to use checkplotserver to see neighbors, etc. of objects):
```python
cpf = checkplot.checkplot_pickle([], times, mags, errs)
```

**Comment by joshuawallace** [comment]
Yep, things are working now.  Thanks!
