### ISSUE TITLE
Checkplots showing exceptional outliers

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#53]
I've appreciated in the past that the checkplots zoom in on the "important" points by automatically discounting some outlier points when determining axis limits.  However, a current checkplot of mine is not doing this, even when I set sigclip to a value.  The entire range of points, including the extreme outliers, is shown.  See attached screenshot for an example.
![screenshot-67](https://user-images.githubusercontent.com/5067798/44497714-e7b42880-a648-11e8-8368-b876edfb31b3.png)

**Comment by waqasbhatti** [comment]
Hmm, that's weird. What value of sigclip did you use for `checkplot.checkplot_pickle` to make the pickle? The default is something like 10.0, which would probably explain this. 

Does the same thing happen when you try the phased LC plot controls for sigclip in the period search tab of the checkplotserver? Might be a bug in sigclip if setting that to something like 1.0 doesn't help.

**Comment by joshuawallace** [comment]
I just noticed that this seems to occur only when I set sigclip to be an integer, rather than a float.  Float values work fine.

**Comment by waqasbhatti** [comment]
I think this was fixed.
