### ISSUE TITLE
buggy BLS depths

### ISSUE THREAD

**Issue by lgbouma** [waqasbhatti/astrobase#77]
The following tarball has a minimal working example (with dependencies from `pipe-trex`, + the lightcurves used):

[bls_example.tar.gz](https://github.com/waqasbhatti/astrobase/files/2715135/bls_example.tar.gz)

The BLS implementation from `kbls` seems to be doing a couple wonky things.
1) sometimes, the returned transit depth seems to sometimes have the wrong sign, e.g., for WASP-29b attached
2) other times (more frequently), the returned depth seems to be systematically too small.

The work-around I've been using for _fast_ transit model-fitting has been to use the BLS period as an initial guess to fit trapezoidal models. This seems to produce robust depths.

However both (1) and (2) above are important to fix. (1) for obvious reasons, (2) because it affects the depths we measure, and thus the measured SNR of peaks.

WASP-4:
![wasp-4b_bls_buggy](https://user-images.githubusercontent.com/13185735/50520143-a61b0a80-0a8c-11e9-8a14-ccc90baa2f9b.png)
WASP-5:
![wasp-5b_bls_buggy](https://user-images.githubusercontent.com/13185735/50520144-a61b0a80-0a8c-11e9-9105-a617bdbeea79.png)
WASP-29:
![wasp-29b_bls_buggy](https://user-images.githubusercontent.com/13185735/50520145-a61b0a80-0a8c-11e9-99c8-1eeefbb1cf78.png)

```
"""
example showing odd BLS behavior.
"""
import numpy as np
from lcstatistics import read_tfa_lc
from astrobase.periodbase import kbls
from astrobase.varbase import lcfit

##########################################
# change things below here

### WASP-29b: fails with transit depth NEGATIVE.
tfalcfile, plname = 'HAT-633-0000416.tfalc', 'WASP-29b'
### WASP-5b: seems ok, but depth is smaller than expected
#tfalcfile, plname = 'HAT-678-0001318.tfalc', 'WASP-5b'
### WASP-4b: seems ok, but depth is smaller than expected
#tfalcfile, plname = 'HAT-717-0001830.tfalc', 'WASP-4b'

# change things above here
##########################################

lc = read_tfa_lc(tfalcfile)

time = lc['btjd']
mag = lc['TF1']
err_mag = lc['RMERR1'] # raw mag err same as TFA mag err

# these zero-points do not matter; we care about relative flux. for the error
# transformation, note
#   sigma_flux = dg/d(mag) * sigma_mag, for g=f0 * 10**(-0.4*(mag-mag0)).
mag_0 = 10
flux_0 = 1000
flux = flux_0 * 10**(-0.4 * (mag - mag_0))
err_flux = np.abs(
    -0.4 * np.log(10) * flux_0 * 10**(-0.4*(mag-mag_0)) * err_mag
)

fluxmedian = np.nanmedian(flux)
flux /= fluxmedian
err_flux /= fluxmedian

# fit BLS model; plot resulting phased LC.
endp = 1.05*(np.nanmax(time) - np.nanmin(time))/2
nworkers=8
blsdict = kbls.bls_parallel_pfind(time, flux, err_flux,
                                  magsarefluxes=True, startp=0.1,
                                  endp=endp, maxtransitduration=0.15,
                                  nworkers=nworkers, sigclip=None)
fitd = kbls.bls_stats_singleperiod(time, flux, err_flux,
                                   blsdict['bestperiod'],
                                   maxtransitduration=0.15,
                                   magsarefluxes=True, sigclip=None,
                                   perioddeltapercent=5)

blsfit_savfile = '{}_bls_buggy.png'.format(plname)
lcfit._make_fit_plot(fitd['phases'], fitd['phasedmags'], None,
                     fitd['blsmodel'], fitd['period'], fitd['epoch'],
                     fitd['epoch'], blsfit_savfile, magsarefluxes=True)

```

**Comment by lgbouma** [comment]
One plausible work-around: switch to Foreman-Mackey's recent astropy BLS contribution. In the relevant areas of `kbls.py`, this would involve calls similar to the below.

For the cases above, this seems to produce reasonable BLS fits. (Though the depths still perhaps are slightly underestimated because of the gap in the TESS data?)

![wasp-4b_bls_astropy](https://user-images.githubusercontent.com/13185735/50796468-b22e7580-129f-11e9-8f50-c583971b1d2e.png)
![wasp-4b_bls_buggy](https://user-images.githubusercontent.com/13185735/50796469-b22e7580-129f-11e9-843d-fe8d9c0b6dfd.png)
![wasp-4b_lc](https://user-images.githubusercontent.com/13185735/50796470-b22e7580-129f-11e9-8f0e-49b79438a14a.png)
![wasp-5b_bls_astropy](https://user-images.githubusercontent.com/13185735/50796471-b22e7580-129f-11e9-9a77-bee99036e9d1.png)
![wasp-5b_bls_buggy](https://user-images.githubusercontent.com/13185735/50796472-b2c70c00-129f-11e9-8b83-ac40d6f1eead.png)
![wasp-5b_lc](https://user-images.githubusercontent.com/13185735/50796473-b2c70c00-129f-11e9-98dc-6fd3ee60a497.png)
![wasp-29b_bls_astropy](https://user-images.githubusercontent.com/13185735/50796475-b2c70c00-129f-11e9-8471-01f092a02720.png)
![wasp-29b_bls_buggy](https://user-images.githubusercontent.com/13185735/50796476-b2c70c00-129f-11e9-8dbe-f51ff98dcef4.png)
![wasp-29b_lc](https://user-images.githubusercontent.com/13185735/50796477-b2c70c00-129f-11e9-9115-2240d04f85b6.png)


```
######################################################
# what if we just used Foreman-Mackey's astropy BLS? #
######################################################
from astropy.stats import BoxLeastSquares
from astropy import units as u

model = BoxLeastSquares(time, flux, dy=err_flux)

# run an initial periodogram using array of transit durations and the
# auto-generated period grid.
tdurnarr = np.linspace(0.05,0.5,100)
results = model.autopower(tdurnarr)

best_period = results.period[np.argmax(results.power)]
best_depth = results.depth[np.argmax(results.power)]
print('initial best depth {:.2e}'.format(best_depth))
print('for {}, got initial period {}, refining...'.format(plname, best_period))

# run a finer (probably) grid using the best period from the auto-generated
# grid.
periods = np.linspace(best_period-0.5, best_period+0.5, 10000)
results = model.power(periods, tdurnarr)

best_period = results.period[np.argmax(results.power)]
best_t0 = results.transit_time[np.argmax(results.power)]
best_durn = results.duration[np.argmax(results.power)]
best_depth = results.depth[np.argmax(results.power)]
print('depth {:.2e}'.format(best_depth))
print('refined period {}'.format(best_period))

results_stats = model.compute_stats(best_period, best_durn, best_t0)

bls_flux_model = np.ones_like(flux)
for transit_time in results_stats['transit_times']:
    tstart, tend = transit_time - best_durn/2, transit_time + best_durn/2
    bls_flux_model[(time>tstart) & (time<tend)] -= best_depth

pdict = phase_magseries(time, flux, best_period, best_t0,
                        wrap=False, sort=True)
pmodeldict = phase_magseries(time, bls_flux_model, best_period, best_t0,
                             wrap=False, sort=True)

blsfit_savfile = '{}_bls_astropy.png'.format(plname)
lcfit._make_fit_plot(pdict['phase'], pdict['mags'], None,
                     pmodeldict['mags'], best_period, best_t0,
                     best_t0, blsfit_savfile, magsarefluxes=True)
```

**Comment by lgbouma** [comment]
@waqasbhatti , let me know if this solution seems fine and I'll go ahead and PR it. This seems like a better long-term fix given astropy's wide reach, compared to the pyeebls fork.

**Comment by waqasbhatti** [comment]
I think the problem might lie in how eebls.f handles positive vs negative transit depths based on a quick look at its source. I'll look into it a bit more soon.

In the meantime, I've implemented Astropy's BoxLeastSquares functions in `periodbase.abls`, using an identical API to the existing `periodbase.kbls.bls_{serial,parallel}_pfind` functions. These only work for Astropy >= 3.1 (and Python >= 3). Still working out some bugs in there and have yet to implement the SNR functions similar to `periodbase.kbls`, but it should be OK to play with for the time being.

**Comment by waqasbhatti** [comment]
These are tests of the data above with the newest `kbls.bls_stats_singleperiod`, which uses `lcfit.traptransit_fit_magseries` to fit a trapezoid transit and get a better estimate of the depth, duration, etc. that way. 

```python
import numpy as np
import pandas as pd
from astrobase.periodbase import kbls
from astrobase.varbase import lcfit

lc = pd.read_csv('waspXX-lc.tfalc',delim_whitespace=True,header=None)
times, mags, errs = np.array(lc[0]), np.array(lc[30]), np.array(lc[15])
blsres = kbls.bls_parallel_pfind(times,mags,errs,sigclip=None,maxtransitduration=0.2,magsarefluxes=False)
stats = kbls.bls_stats_singleperiod(times,mags,errs,blsres['bestperiod'],ingressdurationfraction=0.1,sigclip=None,maxtransitduration=0.2,magsarefluxes=False)
lcfit._make_fit_plot(stats['phases'], stats['phasedmags'], None,
                     stats['blsmodel'], stats['period'], stats['epoch'],
                     stats['epoch'], 'waspXX.png', magsarefluxes=False, wrap=True)
```

I think for WASP29, eebls.f is being thrown off by sinusoidal variability. I'm not sure if it checks for always fainter transit features, so that's one thing to look into. For the other ones, the new stats function appears to work correctly now.

Using mags:

WASP4
![wasp4](https://user-images.githubusercontent.com/1868184/52816105-85c00300-306e-11e9-8785-8a8711b14766.png)

WASP5
![wasp5](https://user-images.githubusercontent.com/1868184/52816114-8bb5e400-306e-11e9-927c-098189f89e5b.png)

WASP29
![wasp29](https://user-images.githubusercontent.com/1868184/52816119-8fe20180-306e-11e9-9ba9-fb5819a0e319.png)

Checking with fluxes now and using `magsarefluxes=True` as appropriate:

WASP4
![wasp4-fluxes](https://user-images.githubusercontent.com/1868184/52816790-07fcf700-3070-11e9-929f-26ebae7d0a31.png)

WASP5
![wasp5-fluxes](https://user-images.githubusercontent.com/1868184/52816941-5c07db80-3070-11e9-9bc9-caded7b0174c.png)

WASP29
![wasp29-fluxes](https://user-images.githubusercontent.com/1868184/52817026-a426fe00-3070-11e9-956a-039ff4999b92.png)

**Comment by waqasbhatti** [comment]
It's a bit of work, but prewhitening the LC makes the BLS fit correct:

```python
from astrobase.varbase import signals

# mask out the transit first
masked = signals.mask_signal(times,mags,errs,blsres['bestperiod'],1364.21365,maskphaselength=0.05,sigclip=None,maskphases=[0.0,1.0], plotfit='masked.png')
```
![masked](https://user-images.githubusercontent.com/1868184/52818384-a25f3980-3074-11e9-8f89-5ec7fa113851.png)
```python
# fourier fit the remaining signal
ffit = lcfit.fourier_fit_magseries(masked['mtimes'],masked['mmags'],masked['merrs'],stats['period'],fourierorder=2,plotfit='ffit.png')
```
![ffit](https://user-images.githubusercontent.com/1868184/52818442-cae73380-3074-11e9-9bed-cd533582763e.png)
```python
# prewhiten using the fit period and fourier params
whitened = signals.prewhiten_magseries(times,mags,errs,stats['period'],ffit['fitinfo']['finalparams'],sigclip=None,plotfit='whitened.png')
```
![whitened](https://user-images.githubusercontent.com/1868184/52818483-ea7e5c00-3074-11e9-956b-7c7266ca9c8e.png)

Then running `bls_stats_singleperiod` works correctly:
```python
stats = kbls.bls_stats_singleperiod(whitened['wtimes'],whitened['wmags'],whitened['werrs'],blsres['bestperiod'],ingressdurationfraction=0.1,sigclip=None,maxtransitduration=0.2,magsarefluxes=False,perioddeltapercent=10)
lcfit._make_fit_plot(stats['phases'], stats['phasedmags'], None,stats['blsmodel'], stats['period'], stats['epoch'],stats['epoch'], 'wasp29-whitened.png', magsarefluxes=False, wrap=True)
```
![wasp29-whitened](https://user-images.githubusercontent.com/1868184/52818570-1e598180-3075-11e9-87e0-228735fd1f7f.png)

**Comment by lgbouma** [comment]
Nice! Thank you for looking closely through these examples.

I agree that once the period is known, measuring the SNR using the trapezoidal model is a good patch. However for purposes of period-finding, it would be best if the power of BLS periodogram was a good measurement of the best-fitting SNR. (Which requires a decent depth and duration match).

DFM's astropy BLS (as you've wrapped in `abls`) solves the period-finding problem, because its depths aren't too shallow ([these plots](https://github.com/waqasbhatti/astrobase/issues/77#issuecomment-452101137)). But it has speed problems that we discussed on Friday.

A hitherto unmentioned BLS implementation that solves both the period-finding problem and the speed problem is the VARTOOLS implementation. For my own need to run BLS on many lightcurves, I might just opt for this. But this isn't an astrobase-internal solution.

One solution would be to deprecate `kbls` in favor of `abls` in some future release.
Another is to find & understand whatever is causing the shallow depths from `eebls.f`.
A final one (perhaps coupled with `kbls` deprecation) would be to add VARTOOLS TFA as a dependency.

It's surprising to me that the `eebls.f` & astropy BLS results are qualitatively so different. Suggests there's really something different happening in the implementations!

**Comment by waqasbhatti** [comment]
`periodbase.kbls` now uses `scipy.optimize.curve_fit` to do its trapezoid transit fits and can use parameter bounds to make sure the fit makes sense for mags vs. flux, ingress duration vs. total transit duration, etc. This appears to fix the problem encountered in the WASP29 fit above when `kbls.get_stats_singleperiod` is called or `kbls.bls_parallel_pfind` is called with `get_stats=True` without having to resort to additional trickery.

![wasp29](https://user-images.githubusercontent.com/1868184/58833379-e45dbc80-861e-11e9-9533-21df04e98538.png)
