### ISSUE TITLE
'blsresult' key error

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#81]
I just tried running the latest commit of astrobase and got the following error:

>   File "astrobase_search.py", line 207, in main
>    bls = >periodbase.bls_parallel_pfind(times,mags,errs,startp=pmin,endp=maximum_obs_length[obj],nphasebins=200,mintransitduration=.02,maxtransitduration=.55,nbestpeaks=3,sigclip=sigclipvalue,nworkers=njobs,verbose=False)
 > File >"/nfs/phs3/ar0/S/PROJ/jwallace/m4/vetting_signals/periodogram_snr_analysis/transit_inject/astrobase_aaa/periodbase/kbls.py", line 1011, in bls_parallel_pfind
 >   verbose=verbose,
 > File >"/nfs/phs3/ar0/S/PROJ/jwallace/m4/vetting_signals/periodogram_snr_analysis/transit_inject/astrobase_aaa/periodbase/kbls.py", line 1422, in bls_stats_singleperiod
>    thistransdepth = blsres['blsresult']['transdepth']
>KeyError: 'blsresult'

I thought this might be connected with yesterday's changes so I wanted to mention it here.

**Comment by waqasbhatti** [comment]
I think this happened because BLS failed on the light curve. The function didn't return a 'blsresult' key in this instance so the stats function also failed. Can you point me to the LC involved or send it over?

**Comment by joshuawallace** [comment]
Yes, I see the "BLS failed!" messages now.

It's a script that runs just fine on my environment's version of astrobase
(v0.4.0).  When I switch over to a local directory with last night's most
recent commit of astrobase is when it starts failing.  It fails on the
first light curve, which makes me think it might fail on all.

I'll PM a link to the relevant files.

**Comment by joshuawallace** [comment]
Things are working now with the commit, thanks!
