### ISSUE TITLE
[minor tweak] tfa n_templates should depend on time baseline

### ISSUE THREAD

**Issue by lgbouma** [waqasbhatti/astrobase#82]
https://github.com/waqasbhatti/astrobase/blob/d2d6d73c233e2e8ea9ff0058921e12c8eb3d6a2b/astrobase/lcproc/tfa.py#L415

The qualitative number for "how many parameters should I fit to this lightcurve?" is the number of points in the lightcurve, rather than the number of stars in the field.

E.g., in a v-v-crowded field with 1e6 stars, the 10% parameter would give 1e5 coefficients to detrend against in your lightcurve, irrespective of how many points are in the LC. For the typical ~few thousand points, this would lead to overfitting!

**Comment by waqasbhatti** [comment]
This is handled here, I think:

https://github.com/waqasbhatti/astrobase/blob/d2d6d73c233e2e8ea9ff0058921e12c8eb3d6a2b/astrobase/lcproc/tfa.py#L878

**Comment by lgbouma** [comment]
Correct. My bad!
