### ISSUE TITLE
tuple should be and

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#83]
https://github.com/waqasbhatti/astrobase/blob/5781850098b4257c96a535127735ec936f0b41cd/astrobase/varclass/starfeatures.py#L1411

The if statement here seems incorrect, particularly when compared with e.g. line 1372.  All the if is doing here is seeing if the tuple that this statement is creating exists, when it seems like the comma at the end of the line should be an "and" so everything gets checked.

**Comment by waqasbhatti** [comment]
Yep, that's definitely a typo. Not sure why it wasn't a breaking compile error, but should be fixed now.

Thanks!
