### ISSUE TITLE
Possible bug in CSV file update for checkplots

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#85]
I was looking at the CSV file generated by the checkplot server for all the checkplots I looked at.  I noticed that the varinfo.objectisvar flag was sometimes set to a decimal number (rather than 1, 2, or 3), and sometimes corresponding the varinfo.varperiod was set to 1, 2, or 3.  I was thinking that maybe the two of these were sometimes getting switched?  Here's a screenshot.
![screenshot_varinfo](https://user-images.githubusercontent.com/5067798/57338756-8a8bd480-70fc-11e9-988d-9267fa9f1c88.jpg)

**Comment by waqasbhatti** [comment]
Yep, this is probably a bug somewhere in the JS for the frontend. Can you point me to the checkplotlist JSON file for this session?

**Comment by joshuawallace** [comment]
Sorry I never got around to checking this.

**Comment by waqasbhatti** [comment]
I think I got it working, but it's all moot now :-)
