### ISSUE TITLE
port imageutils fits reading functions?

### ISSUE THREAD

**Issue by lgbouma** [waqasbhatti/astrobase#88]
[suggestion]

`pipe-trex/imageutils.py` has some FITS read functions that I use all the time, mainly just to write less code.

This issue suggests either (a) moving the entire `imageutils.py` function collection, or else (b) the following functions to a new `astrobase/imageutils.py` file:

```
read_fits
read_fits_header
get_header_keyword
get_header_keyword_list
get_data_keyword
get_data_keyword_list (not implemented, but I can write it).
```

For TESS/Kepler/K2 processing, this would be helpful!  Let me know if you think this would be useful, and I can write it up.

**Comment by waqasbhatti** [comment]
Sounds good to me. Let's go with option (b) for now.

It might be better in the long run if I broke out the more extensive pipe-trex2 imageutils subpackage into a new package on github/pypi.
